apiVersion: v1
kind: ConfigMap
metadata:
  name: flask-config-map
data:
  USER: Ashry Ramadhan
  TOKEN: "777"
  VERSION: 1.0.0

---

apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: simple-flask
spec:
  replicas: 3
  selector:
    matchLabels:
      project: simple-flask
  template:
    metadata:
      name: simple-flask-pod
      labels:
        project: simple-flask
    spec:
      containers:
        - name: simple-flask
          image: localhost:5000/simple-flask
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef: # this part is important
                name: flask-config-map

---

apiVersion: v1
kind: Service
metadata:
  name: simple-flask-service
spec:
  type: NodePort
  selector:
    project: simple-flask
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30001