apiVersion: batch/v1
kind: Job
metadata:
  name: python-job
spec:
  completions: 5
  parallelism: 2
  template:
    metadata:
      name: python-job-pod
      annotations:
        author: ashry ramadhan
        topic: learn kubernetes job
    spec:
      restartPolicy: Never # -> docker
      containers:
        - name: python-job
          image: ashryramadhan10/python-hello-world:latest