apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: nginx-rs
spec:
  replicas: 3
  selector:
    matchLabels:
      project: node-port-service
  template:
    metadata:
      name: nginx-pod
      labels:
        project: node-port-service
    spec:
      containers:
        - name: nginx
          image: ashryramadhan10/nginx-curl
          ports:
            - containerPort: 80

---

apiVersion: v1
kind: Service
metadata:
  name: node-port-service
spec:
  type: NodePort
  selector:
    project: node-port-service
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30001
  