apiVersion: v1
kind: ConfigMap
metadata:
  name: simple-flask-config
data:
  APPLICATION: My Cool Application

---

apiVersion: v1
kind: Secret
metadata:
  name: simple-flask-secret
stringData:
  VERSION: 1.0.0

---

apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: simple-flask
spec:
  replicas: 3
  selector:
    matchLabels:
      name: simple-flask
  template:
    metadata:
      name: simple-flask
      labels:
        name: simple-flask
    spec:
      containers:
        - name: simple-flask
          image: localhost:5000/simple-flask
          ports:
            - containerPort: 3000
          envFrom:
            - configMapRef:
                name: simple-flask-config
            - secretRef:
                name: simple-flask-secret

---

apiVersion: v1
kind: Service
metadata:
  name: simple-flask-service
spec:
  type: NodePort
  selector:
    name: simple-flask
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 30001